version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Game_of_Thrones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./lab_01:/docker-entrypoint-initdb.d
      - ./data:/data
    ports:
      - "5432:5432"
