version: "3.9"

services:
  postgres:
    build: ./
    environment:
      POSTGRES_DB: RK2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./scr:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
