DROP VIEW IF EXISTS OAC_v;
DROP TRIGGER IF EXISTS DELETE_OAC on OAC_v;

DROP FUNCTION IF EXISTS OAC_V_DELETE_INFO();

CREATE OR REPLACE FUNCTION OAC_V_DELETE_INFO()
RETURNS trigger
AS $$
BEGIN
    RAISE NOTICE 'The OAC_v has been updated';

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW OAC_v
AS
SELECT id_organization, id_character, state, years_in from organ_and_charac;

CREATE TRIGGER DELETE_OAC
INSTEAD OF DELETE
on OAC_v
FOR EACH ROW
EXECUTE PROCEDURE OAC_V_DELETE_INFO();

delete from OAC_v where id_character = 7;